MIGRATIONS_PATH=./src/migrations

migration-generate:
	yarn migration:generate ${MIGRATIONS_PATH}/${name}

migration-run:
	yarn migration:run

migration-show:
	yarn migration:show

migration-revert:
	yarn migration:revert
